spring:
  datasource:
    name: testa
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean