package com.example.demo.entity;

import java.io.Serializable;

public class Dishes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.dishid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Integer dishid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.dname
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.price
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.intro
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.detail
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.type
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.dishpic
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private String dishpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.dishid
     *
     * @return the value of dishes.dishid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Integer getDishid() {
        return dishid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.dishid
     *
     * @param dishid the value for dishes.dishid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setDishid(Integer dishid) {
        this.dishid = dishid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.dname
     *
     * @return the value of dishes.dname
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.dname
     *
     * @param dname the value for dishes.dname
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.price
     *
     * @return the value of dishes.price
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.price
     *
     * @param price the value for dishes.price
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.intro
     *
     * @return the value of dishes.intro
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.intro
     *
     * @param intro the value for dishes.intro
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.detail
     *
     * @return the value of dishes.detail
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.detail
     *
     * @param detail the value for dishes.detail
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.type
     *
     * @return the value of dishes.type
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.type
     *
     * @param type the value for dishes.type
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.dishpic
     *
     * @return the value of dishes.dishpic
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public String getDishpic() {
        return dishpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.dishpic
     *
     * @param dishpic the value for dishes.dishpic
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setDishpic(String dishpic) {
        this.dishpic = dishpic == null ? null : dishpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dishid=").append(dishid);
        sb.append(", dname=").append(dname);
        sb.append(", price=").append(price);
        sb.append(", intro=").append(intro);
        sb.append(", detail=").append(detail);
        sb.append(", type=").append(type);
        sb.append(", dishpic=").append(dishpic);
        sb.append("]");
        return sb.toString();
    }
}