package com.example.demo.entity;

import java.io.Serializable;

public class DishOrder extends DishOrderKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishorder.dishsta
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Integer dishsta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishorder.count
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dishorder
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishorder.dishsta
     *
     * @return the value of dishorder.dishsta
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Integer getDishsta() {
        return dishsta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishorder.dishsta
     *
     * @param dishsta the value for dishorder.dishsta
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setDishsta(Integer dishsta) {
        this.dishsta = dishsta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishorder.count
     *
     * @return the value of dishorder.count
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishorder.count
     *
     * @param count the value for dishorder.count
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dishsta=").append(dishsta);
        sb.append(", count=").append(count);
        sb.append("]");
        return sb.toString();
    }
}