package com.example.demo.entity;

import java.io.Serializable;

public class DishOrderKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishorder.order_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishorder.dish_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private Integer dishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishorder.order_id
     *
     * @return the value of dishorder.order_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishorder.order_id
     *
     * @param orderId the value for dishorder.order_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishorder.dish_id
     *
     * @return the value of dishorder.dish_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public Integer getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishorder.dish_id
     *
     * @param dishId the value for dishorder.dish_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setDishId(Integer dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", dishId=").append(dishId);
        sb.append("]");
        return sb.toString();
    }
}