package com.example.demo.entity;

import java.io.Serializable;

public class DishOrder extends DishOrderKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishorder.dish_state
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private Integer dishState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishorder.count
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishorder.dish_state
     *
     * @return the value of dishorder.dish_state
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public Integer getDishState() {
        return dishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishorder.dish_state
     *
     * @param dishState the value for dishorder.dish_state
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setDishState(Integer dishState) {
        this.dishState = dishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishorder.count
     *
     * @return the value of dishorder.count
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishorder.count
     *
     * @param count the value for dishorder.count
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dishState=").append(dishState);
        sb.append(", count=").append(count);
        sb.append("]");
        return sb.toString();
    }
}