package com.example.demo.entity;

import java.io.Serializable;

public class Notice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_id
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.user_id
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.contents
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    private String contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.send_time
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    private String sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notice
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_id
     *
     * @return the value of notice.notice_id
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_id
     *
     * @param noticeId the value for notice.notice_id
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.user_id
     *
     * @return the value of notice.user_id
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.user_id
     *
     * @param userId the value for notice.user_id
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.contents
     *
     * @return the value of notice.contents
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.contents
     *
     * @param contents the value for notice.contents
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.send_time
     *
     * @return the value of notice.send_time
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.send_time
     *
     * @param sendTime the value for notice.send_time
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime == null ? null : sendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Thu Feb 24 09:38:47 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", noticeId=").append(noticeId);
        sb.append(", userId=").append(userId);
        sb.append(", contents=").append(contents);
        sb.append(", sendTime=").append(sendTime);
        sb.append("]");
        return sb.toString();
    }
}