package com.example.demo.entity;

import java.io.Serializable;

public class Notice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.nid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Integer nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.uid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.contents
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private String contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notice
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.nid
     *
     * @return the value of notice.nid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.nid
     *
     * @param nid the value for notice.nid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.uid
     *
     * @return the value of notice.uid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.uid
     *
     * @param uid the value for notice.uid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.contents
     *
     * @return the value of notice.contents
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.contents
     *
     * @param contents the value for notice.contents
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nid=").append(nid);
        sb.append(", uid=").append(uid);
        sb.append(", contents=").append(contents);
        sb.append("]");
        return sb.toString();
    }
}