package com.example.demo.entity;

import java.io.Serializable;

public class OrderInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.oid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderNO
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Integer orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.tableid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Integer tableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.ordersta
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Integer ordersta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.totalprice
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private Double totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.oid
     *
     * @return the value of orderinfo.oid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.oid
     *
     * @param oid the value for orderinfo.oid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderNO
     *
     * @return the value of orderinfo.orderNO
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderNO
     *
     * @param orderno the value for orderinfo.orderNO
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.tableid
     *
     * @return the value of orderinfo.tableid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Integer getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.tableid
     *
     * @param tableid the value for orderinfo.tableid
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setTableid(Integer tableid) {
        this.tableid = tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.ordersta
     *
     * @return the value of orderinfo.ordersta
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Integer getOrdersta() {
        return ordersta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.ordersta
     *
     * @param ordersta the value for orderinfo.ordersta
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setOrdersta(Integer ordersta) {
        this.ordersta = ordersta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.totalprice
     *
     * @return the value of orderinfo.totalprice
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.totalprice
     *
     * @param totalprice the value for orderinfo.totalprice
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oid=").append(oid);
        sb.append(", orderno=").append(orderno);
        sb.append(", tableid=").append(tableid);
        sb.append(", ordersta=").append(ordersta);
        sb.append(", totalprice=").append(totalprice);
        sb.append("]");
        return sb.toString();
    }
}