package com.example.demo.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.profile_pic
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private String profilePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_lock
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private Integer isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role_id
     *
     * @return the value of user.role_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role_id
     *
     * @param roleId the value for user.role_id
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.profile_pic
     *
     * @return the value of user.profile_pic
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public String getProfilePic() {
        return profilePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.profile_pic
     *
     * @param profilePic the value for user.profile_pic
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic == null ? null : profilePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_lock
     *
     * @return the value of user.is_lock
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_lock
     *
     * @param isLock the value for user.is_lock
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", password=").append(password);
        sb.append(", roleId=").append(roleId);
        sb.append(", profilePic=").append(profilePic);
        sb.append(", isLock=").append(isLock);
        sb.append("]");
        return sb.toString();
    }
}