package com.example.demo.dao;

import com.example.demo.entity.DishOrder;
import com.example.demo.entity.DishOrderExample;
import com.example.demo.entity.DishOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DishOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int countByExample(DishOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int deleteByExample(DishOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int deleteByPrimaryKey(DishOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int insert(DishOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int insertSelective(DishOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    List<DishOrder> selectByExample(DishOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    DishOrder selectByPrimaryKey(DishOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int updateByExampleSelective(@Param("record") DishOrder record, @Param("example") DishOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int updateByExample(@Param("record") DishOrder record, @Param("example") DishOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int updateByPrimaryKeySelective(DishOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishorder
     *
     * @mbggenerated Thu Feb 24 15:34:35 CST 2022
     */
    int updateByPrimaryKey(DishOrder record);
}