package com.example.demo.dao;

import com.example.demo.entity.Dishes;
import com.example.demo.entity.DishesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DishesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int countByExample(DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int deleteByExample(DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int deleteByPrimaryKey(Integer dishid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int insert(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int insertSelective(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    List<Dishes> selectByExample(DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    Dishes selectByPrimaryKey(Integer dishid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") Dishes record, @Param("example") DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int updateByExample(@Param("record") Dishes record, @Param("example") DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int updateByPrimaryKeySelective(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated Wed Feb 23 14:22:03 CST 2022
     */
    int updateByPrimaryKey(Dishes record);
}